app/models/__init__.py
#coding: utf-8

from .user import User

app/models/user.py
# coding: utf-8
from app import app

class User():
    def __init__(self, username):
        self.init_user(username)

    @staticmethod
    def query(username, password):
        for item in app.config['USER']:
            if username == item['username'] and password == item['password']:
                return User(username)

        return None

    def init_user(self, username):
        for item in app.config['USER']:
            if username == item['username']:
                self.username = username
                self.print_name = item['print_name']
                self.print_role = item['print_role']
                self.role = item['role']
                self.index = self.role + '.index'

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return str(self.username)

app/__init__.py
#coding: utf-8

from flask import Flask

app = Flask(__name__)
app.config.from_object('config')

from .views import mainView

app.register_blueprint(mainView, url_prefix='/main')

app/views/__init__.py
# coding: utf-8
from app import app
from app.models import User
from flask import render_template, redirect, url_for, request, g
from flask_login import LoginManager, login_user, logout_user, current_user
from .main import mainView


login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'login'
login_manager.login_message = '请登陆'


@app.before_request
def before_request():
    g.user = current_user

@app.route('/')
def index():
    if current_user.is_anonymous:
        return redirect(url_for('login'))

    index_url = g.user.role + '.' + 'index'
    return redirect(url_for(index_url))

@app.route('/login', methods=['GET','POST'])
def login():
    if request.method == 'GET':
        return render_template('login/login.html')

    username = request.form['username']
    password = request.form['password']

    user = User.query(username, password)

    if user is None:
        return redirect(url_for('login'))

    login_user(user)
    return redirect(request.args.get('next') or url_for(user.index))


@app.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('login'))


@login_manager.user_loader
def load_user(username):
    return  User(username)

app/views/main.py
# coding: utf-8
from flask import render_template,  Blueprint
from flask_login import login_required

mainView = Blueprint('main', __name__)

@mainView.route('/')
@login_required
def index():
    return render_template('main/pages/main.html',
        content_title='收视概况')

@mainView.route('/tvcrm/')
@login_required
def tvcrm():
    return render_template('main/pages/tvcrm.html',
            content_title='频道统计')

@mainView.route('/tv_analysis/')
@login_required
def tv_analysis():
    return render_template('main/pages/tv_analysis.html',
            content_title='节目统计')

@mainView.route('/user_analysis/')
@login_required
def user_analysis():
    return render_template('main/pages/user_analysis.html',
            content_title='在线人数统计')

@mainView.route('/time_analysis/')
@login_required
def time_analysis():
    return render_template('main/pages/time_analysis.html',
            content_title='收视时长分析')

@mainView.route('/action_analysis/')
@login_required
def action_analysis():
    return render_template('main/pages/action_analysis.html',
            content_title='用户行为分析')

@mainView.route('/user_info/')
@mainView.route('/user_info/<int:user_id>')
@login_required
def user_info(user_id=None):
    if user_id:
        return render_template('main/pages/user_detail.html',
            content_title='深度用户挖掘',
            content_id=user_id)

    return render_template('main/pages/user_info.html',
        content_title='深度用户挖掘')

@mainView.route('/accurate_adpush/')
@mainView.route('/accurate_adpush/<int:user_id>')
@login_required
def accurate_adpush(user_id=None):
    if user_id:
        return render_template('main/pages/adpush_detail.html',
            content_title='精准广告投放',
            content_id=user_id)

    return render_template('main/pages/accurate_adpush.html',
            content_title='精准广告投放')

@mainView.route('/epg_analysis/')
@login_required
def epg_analysis():
    return render_template('main/pages/epg_analysis.html',
            content_title='EPG展示分析')

app/views/manager.py
# coding: utf-8
from flask import render_template,  Blueprint, request, abort
from flask.ext.login import login_required

managerView = Blueprint('manager', __name__)

@managerView.route('/')
@login_required
def index():
    return render_template('manager/pages/main.html',
        content_title='收视概况')

@managerView.route('/tvcrm/')
@managerView.route('/tvcrm/<int:tv_id>')
@login_required
def tvcrm(tv_id=None):
    if tv_id == 1:
        return render_template('manager/pages/room_detail.html',
            content_title='石家庄金石机房',
            web_3d_url = "#")

    return render_template('manager/pages/tvcrm.html',
            content_title='收视率分析')


@managerView.route('/room/')
@managerView.route('/room/<int:room_name>')
@login_required
def room(room_name=None):
    if room_name == 1:
        return render_template('manager/pages/room_detail.html',
            content_title='石家庄金石机房',
            web_3d_url = "#")

    return render_template('manager/pages/room.html',
            content_title='机房资源统计')

@managerView.route('/flow/')
@login_required
def flow():
    return render_template('manager/pages/flow.html',
            content_title='流量核算')

@managerView.route('/port/', methods=['GET'])
@login_required
def port():
    try:
        port_name = request.args.get('port').strip("\"")
        dev_name = request.args.get('device').strip("\"")
        month_value = request.args.get('month').strip("\"")
    except:
        return abort(404)

    return render_template('manager/pages/port.html',
            port_name = port_name,
            dev_name = dev_name,
            month_value = month_value,
            content_title='端口详情')

@managerView.route('/business/')
@login_required
def business():
    return render_template('manager/pages/business.html',
            content_title='收入评估')


@managerView.route('/customer/')
@login_required
def customer():
    return render_template('manager/pages/customer.html',
            content_title='客户评估')

@managerView.route('/analyze-room/')
@login_required
def analyze_room():
    return render_template('manager/pages/analyze_room.html',
            content_title='机房投资分析')

@managerView.route('/analyze-business/')
@login_required
def analyze_business():
    return render_template('manager/pages/analyze_business.html',
            content_title='业务投资分析')

app/templates/base/header.html
<header class="main-header">

    <a href="{{ url_for('main.index') }}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>{{ config['LOGO_TITLE'] }}</b>LT</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>{{ config['LOGO_TITLE'] }}</b></span>
    </a>

    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">

                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ url_for('static', filename='vendor/adminlte/dist/img/user2-160x160.jpg') }}" class="user-image" alt="User Image"/>
                        <span class="hidden-xs">{{ g.user.print_name }}</span>
                    </a>

                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="{{ url_for('static', filename='vendor/adminlte/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image" />
                            <p>
                                <span class="zh">{{ g.user.print_name }}</span>
                                <small class="zh">{{ g.user.print_role }}</small>
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat zh">设置</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ url_for('logout') }}" class="btn btn-default btn-flat">登出</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>

    </nav>
</header>

app/templates/main/pages/main.html
{% extends 'main/layout.html' %}

{% block css %}
{{ super() }}
<link href="{{ url_for('static', filename='vendor/datatables/css/dataTables.bootstrap.css') }}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}

<!-- Main content -->
<section class="content">

    <!-- 四方块 -->
    <div class="row">

        <div class="col-sm-3">
            <!-- 当日在线用户 -->
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3>
                        29.6<sup style="font-size: 18px" class="zh">&nbsp;万</sup>
                    </h3>
                    <p class="zh">
                        当前在线用户
                    </p>
                </div>
                <div class="icon">
                    <i class="ion ion-android-contacts"></i>
                </div>
                <a href="{{ url_for('main.user_analysis') }}" class="small-box-footer">
                    <span class="zh">详情</span>
                    <i class="fa fa-arrow-circle-right"></i>
                </a>
            </div>
        </div><!-- ./col -->

         <div class="col-sm-3">
            <!-- 平均观看时长 -->
            <div class="small-box bg-green">
                <div class="inner">
                    <h3>
                        3.2<sup style="font-size: 20px" class="zh">&nbsp;小时</sup>
                    </h3>
                    <p class="zh">
                        平均观看时长
                    </p>
                </div>
                <div class="icon">
                    <i class="ion ion-android-time"></i>
                </div>
                <a href="{{ url_for('main.time_analysis') }}" class="small-box-footer">
                    <span class="zh">详情</span>
                    <i class="fa fa-arrow-circle-right"></i>
                </a>
            </div>
        </div><!-- ./col -->

        <div class="col-sm-3">
            <!-- 广告收看率 -->
            <div class="small-box bg-yellow">
                <div class="inner">
                    <h3>
                        82.6<sup style="font-size: 20px">&nbsp;%</sup>
                    </h3>
                    <p class="zh">
                        广告投放率
                    </p>
                </div>
                <div class="icon">
                    <i class="ion ion-ios-eye"></i>
                </div>
                <a href="{{ url_for('main.accurate_adpush') }}" class="small-box-footer">
                    <span class="zh">详情</span>
                    <i class="fa fa-arrow-circle-right"></i>
                </a>
            </div>
        </div><!-- ./col -->


        <div class="col-sm-3">
            <!-- 最高收视率 -->
            <div class="small-box bg-red">
                <div class="inner">
                    <h3>
                        1.27<sup style="font-size: 18px" class="zh">&nbsp;%</sup>
                    </h3>
                    <p class="zh">
                        最高收视率
                    </p>
                </div>
                <div class="icon">
                    <i class="ion ion-trophy"></i>
                </div>
                <a href="{{ url_for('main.tvcrm') }}" class="small-box-footer">
                    <span class="zh">详情</span>
                    <i class="fa fa-arrow-circle-right"></i>
                </a>
            </div>
        </div><!-- ./col -->

    </div><!-- / 四方块 -->

    <!-- 用户在线统计 -->
    <div class="row">
        <div class="col-lg-12 col-sm-12">
            <!-- 用户在线统计 -->
            <div class="box box-solid">
                <!-- Custom tabs -->
                <div class="nav-tabs-custom">
                    <!-- Tabs within a box -->
                    <ul class="nav nav-tabs pull-right">
                        <li><a href="#online-pane" data-toggle="tab">
                            <span class="zh">在线总计</span></a>
                        </li>
                        <li class="active"><a href="#online-chart-group" data-toggle="tab">
                            <span class="zh">在线分布</span></a>
                        </li>
                        <li class="pull-left header"><i class="fa fa-users"></i>
                            <span class="zh">用户在线统计</span>
                        </li>
                    </ul>

                    <div class="tab-content no-padding">
                        <!-- 在线总计 -->
                        <div class="tab-pane" id="online-pane">
                            <table id="online-table" class="table table-striped table-bordered"></table>
                        </div>

                         <!-- 在线分布 -->
                        <div class="tab-pane active" id="online-chart-group">
                            <div class="col-sm-5 col-lg-5">
                                <div id="online-chart1" class="main-chart"></div>
                            </div>
                            <div class="col-sm-7 col-lg-7">
                                <div id="online-chart2" class="main-chart"></div>
                            </div>
                        </div>
                    </div>
                </div><!-- /.nav-tabs-custom -->

            </div><!-- / 用户在线统计 -->

        </div><!-- /. col -->

    </div>

    <!-- 节目收视统计 -->
    <div class="row">
        <div class="col-lg-12 col-sm-12">
            <!-- 节目收视统计 -->
            <div class="box box-solid">
                <!-- Custom tabs -->
                <div class="nav-tabs-custom">
                    <!-- Tabs within a box -->
                    <ul class="nav nav-tabs pull-right">
                        <li><a href="#tv-pane" data-toggle="tab">
                            <span class="zh">收视详情</span></a>
                        </li>
                        <li class="active"><a href="#tv-chart-group" data-toggle="tab">
                            <span class="zh">收视统计</span></a>
                        </li>
                        <li class="pull-left header"><i class="fa fa-youtube-play"></i>
                            <span class="zh">节目收视统计</span>
                        </li>
                    </ul>

                    <div class="tab-content no-padding">
                        <!-- 机房概况报表 -->
                        <div class="tab-pane" id="tv-pane">
                            <table id="tv-table" class="table table-striped table-bordered"></table>
                        </div>

                        <!-- 收视统计 -->
                        <div class="tab-pane active" id="tv-chart-group">
                            <div class="col-sm-6 col-lg-6">
                                <div id="tv-chart1" class="main-chart"></div>
                            </div>
                            <div class="col-sm-6 col-lg-6">
                                <div id="tv-chart2" class="main-chart"></div>
                            </div>
                        </div>

                    </div>
                </div><!-- /.nav-tabs-custom -->

            </div><!-- / 收入统计 -->

        </div><!-- /.Left col -->

    </div>

</section><!-- /.content -->

{% endblock %}

{% block js %}
{{ super() }}

<!-- hightchart js -->
<script src="{{ url_for('static', filename='vendor/highcharts/highcharts.js') }}" type="text/javascript"></script>

<!-- data table js -->
<script src="{{ url_for('static', filename='vendor/datatables/js/jquery.dataTables.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='vendor/datatables/js/dataTables.bootstrap.js') }}" type="text/javascript"></script>

<!-- page js -->
<script src="{{ url_for('static', filename='custom/appjs/main/main_page.js') }}" type="text/javascript"></script>

{% endblock %}

app/templates/main/sidebar.html
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ url_for('static', filename='vendor/adminlte/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>{{ g.user.print_name }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
                <span class="input-group-btn">
                    <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form>
        <!-- /.search form -->

        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li class="active">
                <a href="{{ url_for('main.index') }}">
                    <i class="fa fa-leaf"></i> <span class="zh">运营概况</span>
                </a>
            </li>

            <li class="treeview">

                <a href="#">
                    <i class="fa fa-database"></i>
                    <span class="zh">收视统计</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>

                <ul class="treeview-menu">
                    <li><a href="{{ url_for('main.tvcrm') }}">
                        <i class="fa fa-angle-double-right"></i> <span class="zh">频道统计</span></a></li>
                    <li><a href="{{ url_for('main.tv_analysis') }}">
                        <i class="fa fa-angle-double-right"></i> <span class="zh">节目统计</span></a></li>
                </ul>

            </li>

            <li class="treeview">

                <a href="#">
                    <i class="fa fa-user"></i>
                    <span class="zh">用户分析</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>

                <ul class="treeview-menu">
                    <li><a href="{{ url_for('main.user_analysis') }}">
                        <i class="fa fa-angle-double-right"></i> <span class="zh">在线人数统计</span></a></li>
                    <li><a href="{{ url_for('main.time_analysis') }}">
                        <i class="fa fa-angle-double-right"></i> <span class="zh">收视时长分析</span></a></li>
                    <li><a href="{{ url_for('main.action_analysis') }}">
                        <i class="fa fa-angle-double-right"></i> <span class="zh">用户行为分析</span></a></li>
                    <li><a href="{{ url_for('main.user_info') }}">
                        <i class="fa fa-angle-double-right"></i> <span class="zh">深度用户挖掘</span></a></li>

                </ul>

            </li>

            <li class="treeview">

                <a href="#">
                    <i class="fa fa-youtube-play"></i>
                    <span class="zh">广告运营</span>
                    <!-- <small class="badge bg-green">new</small> -->
                    <i class="fa fa-angle-left pull-right"></i>
                </a>

                <ul class="treeview-menu">
                    <li><a href="{{ url_for('main.accurate_adpush') }}">
                        <i class="fa fa-angle-double-right"></i> <span class="zh">精准广告投放</span></a></li>
                </ul>

            </li>

        </ul>

    </section>
    <!-- /.sidebar -->
</aside>

app/templates/manager/leftside.html
<!-- Left side column. contains the logo and sidebar -->
<aside class="left-side sidebar-offcanvas">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
                <span class="input-group-btn">
                    <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form>
        <!-- /.search form -->

        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li class="active">
                <a href="{{ url_for('manager.index') }}">
                    <i class="fa fa-video-camera"></i> <span class="zh">收视概况</span>
                </a>
            </li>

            <li class="treeview">

                <a href="#">
                    <i class="fa fa-area-chart"></i>
                    <span class="zh">节目分析</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>

                <ul class="treeview-menu">
                    <li><a href="{{ url_for('manager.tvcrm') }}"><i class="fa fa-angle-double-right"></i> <span class="zh">收视率分析</span></a></li>
                    <li><a href="{{ url_for('manager.flow') }}"><i class="fa fa-angle-double-right"></i> <span class="zh">用户分布</span></a></li>
                </ul>

            </li>

            <li>
                <a href="{{ url_for('manager.business') }}">
                    <i class="fa fa-jpy"></i> <span class="zh">业务收入评估</span>
                </a>
            </li>
            <li>
                <a href="{{ url_for('manager.customer') }}">
                    <i class="fa fa-user"></i> <span class="zh">客户评估</span> <small class="badge pull-right bg-green">new</small>
                </a>
            </li>

        </ul>

    </section>
    <!-- /.sidebar -->
</aside>

app/templates/manager/pages/main.html
{% extends 'manager/layout.html' %}

{% block css %}
{{ super() }}
<link href="{{ url_for('static', filename='vendor/datatables/css/dataTables.bootstrap.css') }}" rel="stylesheet" type="text/css" />
<style>
    .tab-pane {
        position: relative;
        margin: 10px 20px 0 20px;
        height: 400px;
    }
    .star {
        font-size: 16px;
        color: #f39c12;
    }

    .center {
        text-align: center;
    }

    .main-chart {
        height: 400px;
    }
</style>
{% endblock %}

{% block content %}
<!-- Main content -->
<section class="content">

    <!-- 四方块 -->
    <div class="row">

        <div class="col-lg-3 col-md-6">
            <!-- 当日在线用户 -->
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3>
                        21.5<sup style="font-size: 18px" class="zh">&nbsp;万</sup>
                    </h3>
                    <p class="zh">
                        当日在线用户
                    </p>
                </div>
                <div class="icon">
                    <i class="ion ion-android-contacts"></i>
                </div>
                <a href="{{ url_for('manager.customer') }}" class="small-box-footer">
                    <span class="zh">详情</span>
                    <i class="fa fa-arrow-circle-right"></i>
                </a>
            </div>
        </div><!-- ./col -->

         <div class="col-lg-3 col-md-6">
            <!-- 平均观看时长 -->
            <div class="small-box bg-green">
                <div class="inner">
                    <h3>
                        3.2<sup style="font-size: 20px" class="zh">&nbsp;小时</sup>
                    </h3>
                    <p class="zh">
                        平均观看时长
                    </p>
                </div>
                <div class="icon">
                    <i class="ion ion-android-time"></i>
                </div>
                <a href="{{ url_for('manager.room') }}" class="small-box-footer">
                    <span class="zh">详情</span>
                    <i class="fa fa-arrow-circle-right"></i>
                </a>
            </div>
        </div><!-- ./col -->

        <div class="col-lg-3 col-md-6">
            <!-- 广告收看率 -->
            <div class="small-box bg-yellow">
                <div class="inner">
                    <h3>
                        32.6<sup style="font-size: 20px">&nbsp;%</sup>
                    </h3>
                    <p class="zh">
                        广告收看率
                    </p>
                </div>
                <div class="icon">
                    <i class="ion ion-ios-eye"></i>
                </div>
                <a href="{{ url_for('manager.room') }}" class="small-box-footer">
                    <span class="zh">详情</span>
                    <i class="fa fa-arrow-circle-right"></i>
                </a>
            </div>
        </div><!-- ./col -->


        <div class="col-lg-3 col-md-6">
            <!-- 最高收视率 -->
            <div class="small-box bg-red">
                <div class="inner">
                    <h3>
                        1.27<sup style="font-size: 18px" class="zh">&nbsp;%</sup>
                    </h3>
                    <p class="zh">
                        最高收视率
                    </p>
                </div>
                <div class="icon">
                    <i class="ion ion-trophy"></i>
                </div>
                <a href="{{ url_for('manager.business') }}" class="small-box-footer">
                    <span class="zh">详情</span>
                    <i class="fa fa-arrow-circle-right"></i>
                </a>
            </div>
        </div><!-- ./col -->

    </div><!-- / 四方块 -->

    <!-- 用户在线统计 -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <!-- 用户在线统计 -->
            <div class="box box-solid">
                <!-- Custom tabs -->
                <div class="nav-tabs-custom">
                    <!-- Tabs within a box -->
                    <ul class="nav nav-tabs pull-right">
                        <li><a href="#online-pane" data-toggle="tab">
                            <span class="zh">在线总计</span></a>
                        </li>
                        <li class="active"><a href="#online-chart-group" data-toggle="tab">
                            <span class="zh">在线分布</span></a>
                        </li>
                        <li class="pull-left header"><i class="fa fa-users"></i>
                            <span class="zh">用户在线统计</span>
                        </li>
                    </ul>

                    <div class="tab-content no-padding">
                        <!-- 在线总计 -->
                        <div class="tab-pane" id="online-pane">
                            <table id="online-table" class="table table-striped table-bordered"></table>
                        </div>

                         <!-- 在线分布 -->
                        <div class="tab-pane active" id="online-chart-group">
                            <div class="col-md-5 col-lg-5">
                                <div id="online-chart1" class="main-chart"></div>
                            </div>
                            <div class="col-md-7 col-lg-7">
                                <div id="online-chart2" class="main-chart"></div>
                            </div>
                        </div>
                    </div>
                </div><!-- /.nav-tabs-custom -->

            </div><!-- / 用户在线统计 -->

        </div><!-- /. col -->

    </div>

    <!-- 节目收视统计 -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <!-- 节目收视统计 -->
            <div class="box box-solid">
                <!-- Custom tabs -->
                <div class="nav-tabs-custom">
                    <!-- Tabs within a box -->
                    <ul class="nav nav-tabs pull-right">
                        <li><a href="#tv-pane" data-toggle="tab">
                            <span class="zh">收视详情</span></a>
                        </li>
                        <li class="active"><a href="#tv-chart-group" data-toggle="tab">
                            <span class="zh">收视统计</span></a>
                        </li>
                        <li class="pull-left header"><i class="fa fa-youtube-play"></i>
                            <span class="zh">节目收视统计</span>
                        </li>
                    </ul>

                    <div class="tab-content no-padding">
                        <!-- 机房概况报表 -->
                        <div class="tab-pane" id="tv-pane">
                            <table id="tv-table" class="table table-striped table-bordered"></table>
                        </div>

                        <!-- 收视统计 -->
                        <div class="tab-pane active" id="tv-chart-group">
                            <div class="col-md-6 col-lg-6">
                                <div id="tv-chart1" class="main-chart"></div>
                            </div>
                            <div class="col-md-6 col-lg-6">
                                <div id="tv-chart2" class="main-chart"></div>
                            </div>
                        </div>

                    </div>
                </div><!-- /.nav-tabs-custom -->

            </div><!-- / 收入统计 -->

        </div><!-- /.Left col -->

    </div>



</section><!-- /.content -->

{% endblock %}

{% block js %}
{{ super() }}

<!-- hightchart js -->
<script src="{{ url_for('static', filename='vendor/highcharts/highcharts.js') }}" type="text/javascript"></script>

<!-- data table js -->
<script src="{{ url_for('static', filename='vendor/datatables/js/jquery.dataTables.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='vendor/datatables/js/dataTables.bootstrap.js') }}" type="text/javascript"></script>

<!-- page js -->
<script src="{{ url_for('static', filename='custom/appjs/manager/main_page.js') }}" type="text/javascript"></script>

{% endblock %}

app/templates/manager/rightside.html
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        <span class="zh">{{ content_title }}</span>
        <small class="subtitle">IPTV用户行为分析</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ url_for('manager.index') }}"><i class="fa fa-dashboard"></i>
            <span class="zh">主页</span>
        </a></li>
        <li class="active"><span class="zh">{{ content_title }}</span></li>
    </ol>
</section>